// <auto-generated />
namespace CRM_Nomenclatyre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class keys21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(keys21));
        
        string IMigrationMetadata.Id
        {
            get { return "202606201055127_keys21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
