// <auto-generated />
namespace CRM_Nomenclatyre.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.2")]
    public sealed partial class DbUpdate_1906 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DbUpdate_1906));
        
        string IMigrationMetadata.Id
        {
            get { return "202606192056527_DbUpdate_19.06"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
